version: '3.7'
services:
  mysql_docker:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_SERVER_CONTAINER: 'mysql_docker'
    ports:
      - 6603:3306
    expose:
      - 6603
    volumes:
      - mysql_docker:/var/lib/mysql

  adminer_docker:
    image: adminer:4.8.0
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: galkaev
    ports:
      - 9090:8080
    expose:
      - 9090


volumes:
  mysql_docker: